import { StudentStandard } from '../types';

export interface SubjectConfig {
  id: string;
  name: string;
  isGradeOnly?: boolean;
}

export const SUBJECTS_CONFIG: Record<string, SubjectConfig[]> = {
  [StudentStandard.NURSERY]: [
    { id: 'english_w', name: 'English' },
    { id: 'english_o', name: 'English Oral' },
    { id: 'maths_w', name: 'Mathematics' },
    { id: 'maths_o', name: 'Mathematics Oral' },
    { id: 'gk', name: 'General Knowledge' },
    { id: 'rhymes', name: 'Rhymes' },
    { id: 'drawing', name: 'Drawing', isGradeOnly: true },
  ],
  [StudentStandard.LKG]: [
    { id: 'english_w', name: 'English (written)' },
    { id: 'maths_w', name: 'Mathematics (written)' },
    { id: 'english_o', name: 'English Oral' },
    { id: 'maths_o', name: 'Mathematics Oral' },
    { id: 'gk', name: 'General Knowledge' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'rhymes', name: 'Rhymes/ Story' },
    { id: 'drawing', name: 'Drawing', isGradeOnly: true },
  ],
  [StudentStandard.UKG]: [
    { id: 'english_w', name: 'English' },
    { id: 'english_o', name: 'English Oral' },
    { id: 'maths_w', name: 'Mathematics' },
    { id: 'maths_o', name: 'Mathematics Oral' },
    { id: 'gk', name: 'General Knowledge' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'rhymes', name: 'Rhymes/Story' },
    { id: 'drawing', name: 'Drawing', isGradeOnly: true },
  ],
  [StudentStandard.STD1]: [
    { id: 'english', name: 'English' },
    { id: 'maths', name: 'Mathematics' },
    { id: 'grammar', name: 'Grammar' },
    { id: 'evs', name: 'E.V.S' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'hindi', name: 'Hindi' },
    { id: 'gk', name: 'General Knowledge' },
    { id: 'computer', name: 'Computer', isGradeOnly: true },
  ],
  [StudentStandard.STD2]: [
    { id: 'english', name: 'English' },
    { id: 'maths', name: 'Mathematics' },
    { id: 'grammar', name: 'Grammar' },
    { id: 'evs', name: 'E.V.S' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'hindi', name: 'Hindi' },
    { id: 'gk', name: 'General Knowledge' },
    { id: 'computer', name: 'Computer', isGradeOnly: true },
  ],
  [StudentStandard.STD3]: [
    { id: 'english', name: 'English' },
    { id: 'maths', name: 'Mathematics' },
    { id: 'grammar', name: 'Grammar' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'hindi', name: 'Hindi' },
    { id: 'science', name: 'Science' },
    { id: 'social_science', name: 'Social Science' },
    { id: 'gk', name: 'General Knowledge' },
    { id: 'computer', name: 'Computer', isGradeOnly: true },
  ],
  [StudentStandard.STD4]: [
    { id: 'english', name: 'English' },
    { id: 'maths', name: 'Mathematics' },
    { id: 'grammar', name: 'Grammar' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'hindi', name: 'Hindi' },
    { id: 'science', name: 'Science' },
    { id: 'social_science', name: 'Social Science' },
    { id: 'gk', name: 'General Knowledge' },
    { id: 'computer', name: 'Computer', isGradeOnly: true },
  ],
  [StudentStandard.STD5]: [
    { id: 'english', name: 'English' },
    { id: 'maths', name: 'Mathematics' },
    { id: 'grammar', name: 'Grammar' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'hindi', name: 'Hindi' },
    { id: 'science', name: 'Science' },
    { id: 'social_science', name: 'Social Science' },
    { id: 'gk', name: 'General Knowledge' },
    { id: 'computer', name: 'Computer', isGradeOnly: true },
  ],
  [StudentStandard.STD6]: [
    { id: 'english', name: 'English' },
    { id: 'maths', name: 'Mathematics' },
    { id: 'science', name: 'Science' },
    { id: 'grammar', name: 'Grammar' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'hindi', name: 'Hindi' },
    { id: 'sanskrit', name: 'Sanskrit' },
    { id: 'social_science', name: 'Social Science' },
    { id: 'computer', name: 'Computer', isGradeOnly: true },
  ],
  [StudentStandard.STD7]: [
    { id: 'english', name: 'English' },
    { id: 'maths', name: 'Mathematics' },
    { id: 'science', name: 'Science' },
    { id: 'grammar', name: 'Grammar' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'hindi', name: 'Hindi' },
    { id: 'sanskrit', name: 'Sanskrit' },
    { id: 'social_science', name: 'Social Science' },
    { id: 'computer', name: 'Computer', isGradeOnly: true },
  ],
  [StudentStandard.STD8]: [
    { id: 'english', name: 'English' },
    { id: 'maths', name: 'Mathematics' },
    { id: 'science', name: 'Science' },
    { id: 'grammar', name: 'Grammar' },
    { id: 'gujarati', name: 'Gujarati' },
    { id: 'hindi', name: 'Hindi' },
    { id: 'sanskrit', name: 'Sanskrit' },
    { id: 'social_science', name: 'Social Science' },
    { id: 'computer', name: 'Computer', isGradeOnly: true },
  ],
};
